### ISSUE TITLE
Pictures on the same line align weirdly on tablet breakpoint.

### ISSUE THREAD

**Issue by jyoung295** [PurdueMarketingAndMedia/purdueTemplates-2015#85] opened 2019-02-07 20:39 UTC
In Cascade I was able to get two images side-by-side on the same line using two separate content groups, aligning the first to the left, and the second to the right.

When you shrink the screen to tablet, the aligned right image breaks to a new line but retains it's right alignment rather than shrinking the two images to still fit.

Evidence:
![screen shot 2019-02-07 at 3 37 47 pm](https://user-images.githubusercontent.com/8570747/52441422-81d03600-2aee-11e9-9e65-e5bf605ac656.png)

**Comment by jacobvenable** [comment] 2019-02-08 16:26
The `.imageContainer` elements that wrap around these `<img>`s weren't really built for placing images side-by-side as a row of images. They were built just to flow with text content on the page, as seen in the images on our example content page:
https://purduemarketingandmedia.github.io/purdueTemplates-2015/builds/development/templates/content-2.html

As the screen becomes smaller, the `.imageContainer`'s max-width becomes larger so that the images aren't too small. The reason we see the behavior you mentioned at tablet is because at that size, the max-width of the container is 50% but there are also margins placed on each container.

I don't think we should necessarily change this behavior, but it may be worth looking into adding a new element that is just a row images.

**Comment by jyoung295** [comment] 2019-02-08 16:29
Right, I don't know how often this would realistically come up, but I think adding in an option for 2 or 3 images in a row would be appealing to some clients. Especially depending on what direction we go with the pattern libraries in the future, we could work something in.

**Comment by jacobvenable** [comment] 2019-02-08 16:36
I haven't needed something like this very often, but that isn't to say it wouldn't be useful. Perhaps, this could be part of a photo galleries implementation, and we just don't make the images clickable; however, since this is the intended behavior of this element, I'm going to close this specific issue.

**Closed by jacobvenable** 2019-02-08 16:36 UTC
Labels: bug
